
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANDREW
 */
public class Borrowing_Trans extends javax.swing.JFrame {

    /**
     * Creates new form Borrowing_Trans
     */
    public Borrowing_Trans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librarian3 = new javax.swing.JButton();
        librarian4 = new javax.swing.JButton();
        librarian5 = new javax.swing.JButton();
        librarian6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowingtrans = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        librarian3.setBackground(new java.awt.Color(204, 0, 0));
        librarian3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian3.setForeground(new java.awt.Color(255, 255, 255));
        librarian3.setText("STUDENT");
        librarian3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian3ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 226, 48));

        librarian4.setBackground(new java.awt.Color(204, 0, 0));
        librarian4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian4.setForeground(new java.awt.Color(255, 255, 255));
        librarian4.setText("BOOKS AVAILABLE");
        librarian4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian4ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 226, 48));

        librarian5.setBackground(new java.awt.Color(204, 0, 0));
        librarian5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian5.setForeground(new java.awt.Color(255, 255, 255));
        librarian5.setText("PROGRAM");
        librarian5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian5ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 226, 48));

        librarian6.setBackground(new java.awt.Color(204, 0, 0));
        librarian6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian6.setForeground(new java.awt.Color(255, 255, 255));
        librarian6.setText("LIBRARIAN");
        librarian6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian6ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 226, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unza-logo-2 - Copy.jpg"))); // NOI18N
        jLabel1.setText("BORROWING TRANSACTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        borrowingtrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BORROWING RECEIPT", "ISBN", "STUDENT ID", "BORROWED", "RETUERNED", "ISSUE DATE", "RETURN DATE", "LOST"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(borrowingtrans);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 840, 522));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 51, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/various-book-books-college.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1140, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librarian3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian3ActionPerformed
        new Student_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian3ActionPerformed

    private void librarian4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian4ActionPerformed
        new Books_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian4ActionPerformed

    private void librarian5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian5ActionPerformed
        new Program_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian5ActionPerformed

    private void librarian6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian6ActionPerformed
        new Librarian_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)borrowingtrans.getModel();
        String query ="SELECT * FROM library_project.borrowing_transaction";
        try
        {
            Connection c = Connect.ConnectToDB();
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next())
            {
                String borrowingreceipt = rs.getString("BORROWING_RECEIPT");
                int isbn = rs.getInt("ISBN");
                int studentid = rs.getInt("STUDENT_ID");
                boolean borrowed= rs.getBoolean("BORROWED");
                boolean returned = rs.getBoolean("RETURNED");
                String issuedate = rs.getString("BORROWED_DATE");
                String returndate = rs.getString("RETURN_DATE");
                boolean lost= rs.getBoolean("LOST");
                model.addRow(new Object [] {borrowingreceipt,isbn,studentid,borrowed,returned,issuedate,returndate,lost});
            }
            rs.close();
            stm.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrowing_Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrowing_Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrowing_Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrowing_Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrowing_Trans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable borrowingtrans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton librarian3;
    private javax.swing.JButton librarian4;
    private javax.swing.JButton librarian5;
    private javax.swing.JButton librarian6;
    // End of variables declaration//GEN-END:variables
}
