
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANDREW
 */
public class Librarian_table extends javax.swing.JFrame {

    /**
     * Creates new form Librarian_table
     */
    public Librarian_table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librarian = new javax.swing.JButton();
        librarian1 = new javax.swing.JButton();
        librarian2 = new javax.swing.JButton();
        librarian3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librariantable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        librarian.setBackground(new java.awt.Color(204, 0, 0));
        librarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian.setForeground(new java.awt.Color(255, 255, 255));
        librarian.setText("STUDENT");
        librarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianActionPerformed(evt);
            }
        });
        getContentPane().add(librarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 226, 48));

        librarian1.setBackground(new java.awt.Color(204, 0, 0));
        librarian1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian1.setForeground(new java.awt.Color(255, 255, 255));
        librarian1.setText("BOOKS");
        librarian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian1ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 226, 48));

        librarian2.setBackground(new java.awt.Color(204, 0, 0));
        librarian2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian2.setForeground(new java.awt.Color(255, 255, 255));
        librarian2.setText("BOOK TRANSACTION");
        librarian2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian2ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 226, 48));

        librarian3.setBackground(new java.awt.Color(204, 0, 0));
        librarian3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian3.setForeground(new java.awt.Color(255, 255, 255));
        librarian3.setText("PROGRAM");
        librarian3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarian3ActionPerformed(evt);
            }
        });
        getContentPane().add(librarian3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 226, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unza-logo-2 - Copy.jpg"))); // NOI18N
        jLabel1.setText("LIBRARIAN TABLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        librariantable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPOLOYEE ID", "EMPLOYEE NAME", "ROLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(librariantable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 840, 522));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 137, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1088, 0, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/various-book-books-college.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1140, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianActionPerformed
        new Student_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarianActionPerformed

    private void librarian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian1ActionPerformed
        new Books_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian1ActionPerformed

    private void librarian2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian2ActionPerformed
        new Borrowing_Trans().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian2ActionPerformed

    private void librarian3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarian3ActionPerformed
        new Program_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarian3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            DefaultTableModel model = (DefaultTableModel)librariantable.getModel();
        String query ="SELECT * FROM library_project.librarian";
        try
        {
            Connection c = Connect.ConnectToDB();
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next())
            {
                String employeeid = rs.getString("EMPLOYEE_ID");
                String employeename = rs.getString("EMPLOYEE_NAME");
                String role = rs.getString("ROLE");
                model.addRow(new Object [] {employeeid,employeename,role});
            }
            rs.close();
            stm.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton librarian;
    private javax.swing.JButton librarian1;
    private javax.swing.JButton librarian2;
    private javax.swing.JButton librarian3;
    private javax.swing.JTable librariantable;
    // End of variables declaration//GEN-END:variables
}
