/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDREW
 */
public class Program_table extends javax.swing.JFrame {

    /**
     * Creates new form Program_table
     */
    public Program_table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        librarian = new javax.swing.JButton();
        books_available = new javax.swing.JButton();
        program = new javax.swing.JButton();
        booktrans = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        programtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STUDENT ID", "FIRST NAME", "LAST NAME", "CATEGORY", "EMAIL", "GENDER", "PHONE NUMBER", "YEAR OF STUDY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studenttable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        librarian.setBackground(new java.awt.Color(204, 0, 0));
        librarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian.setForeground(new java.awt.Color(255, 255, 255));
        librarian.setText("LIBRARIAN");
        librarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianActionPerformed(evt);
            }
        });
        getContentPane().add(librarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 226, 48));

        books_available.setBackground(new java.awt.Color(204, 0, 0));
        books_available.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        books_available.setForeground(new java.awt.Color(255, 255, 255));
        books_available.setText("BOOKS AVAILABLE");
        books_available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books_availableActionPerformed(evt);
            }
        });
        getContentPane().add(books_available, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 226, 45));

        program.setBackground(new java.awt.Color(204, 0, 0));
        program.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        program.setForeground(new java.awt.Color(255, 255, 255));
        program.setText("STUDENT");
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });
        getContentPane().add(program, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 226, 47));

        booktrans.setBackground(new java.awt.Color(204, 0, 0));
        booktrans.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booktrans.setForeground(new java.awt.Color(255, 255, 255));
        booktrans.setText("BOOK TRANSACTIONS");
        booktrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktransActionPerformed(evt);
            }
        });
        getContentPane().add(booktrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 55));

        programtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "PROGRAM NAME", "SCHOOL", "DURATION OF PROGRAM", "MAJOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        programtable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(programtable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 202, 830, 460));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unza-logo-2 - Copy.jpg"))); // NOI18N
        jLabel1.setText("PROGRAM TABLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 100, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1088, 0, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/various-book-books-college.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianActionPerformed
        new Librarian_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarianActionPerformed

    private void books_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books_availableActionPerformed
       new Borrowing_Trans().setVisible(true);
       dispose();
    }//GEN-LAST:event_books_availableActionPerformed

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
        new Student_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_programActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          DefaultTableModel model = (DefaultTableModel)programtable.getModel();
        String query ="SELECT * FROM library_project.program";
        try
        {
            Connection c = Connect.ConnectToDB();
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next())
            {
                int studentid = rs.getInt("STUDENT_ID");
                String programname = rs.getString("PROGRAM_NAME");
                String school = rs.getString("SCHOOL");
                int durationofprogram = rs.getInt("DURATION_OF_PROGRAM");
                String major = rs.getString("MAJOR");
                model.addRow(new Object [] {studentid,programname,school,durationofprogram,major});
            }
            rs.close();
            stm.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
                          
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void booktransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktransActionPerformed
        new Borrowing_Trans().setVisible(true);
        dispose();
    }//GEN-LAST:event_booktransActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton books_available;
    private javax.swing.JButton booktrans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton librarian;
    private javax.swing.JButton program;
    private javax.swing.JTable programtable;
    private javax.swing.JTable studenttable;
    // End of variables declaration//GEN-END:variables
}
