/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class Student_table extends javax.swing.JFrame {
    /**
     * Creates new form student_table
     */
    public Student_table() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        librarian = new javax.swing.JButton();
        books_available = new javax.swing.JButton();
        program = new javax.swing.JButton();
        booktrans = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "FIRST NAME", "LAST NAME", "CATEGORY", "EMAIL", "GENDER", "PHONE NUMBER", "YEAR OF STUDY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studenttable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 840, 522));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, -1));
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, 30));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 590));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unza-logo-2 - Copy.jpg"))); // NOI18N
        jLabel1.setText("STUDENT TABLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 50));

        librarian.setBackground(new java.awt.Color(204, 0, 0));
        librarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        librarian.setForeground(new java.awt.Color(255, 255, 255));
        librarian.setText("LIBRARIAN");
        librarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianActionPerformed(evt);
            }
        });
        getContentPane().add(librarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 226, 48));

        books_available.setBackground(new java.awt.Color(204, 0, 0));
        books_available.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        books_available.setForeground(new java.awt.Color(255, 255, 255));
        books_available.setText("BOOKS AVAILABLE");
        books_available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books_availableActionPerformed(evt);
            }
        });
        getContentPane().add(books_available, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 226, 45));

        program.setBackground(new java.awt.Color(204, 0, 0));
        program.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        program.setForeground(new java.awt.Color(255, 255, 255));
        program.setText("PROGRAM");
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });
        getContentPane().add(program, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 226, 47));

        booktrans.setBackground(new java.awt.Color(204, 0, 0));
        booktrans.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booktrans.setForeground(new java.awt.Color(255, 255, 255));
        booktrans.setText("BOOK TRANSACTIONS");
        booktrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktransActionPerformed(evt);
            }
        });
        getContentPane().add(booktrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 55));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1088, 0, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/various-book-books-college.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
        new Program_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_programActionPerformed

    private void books_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books_availableActionPerformed
        new Books_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_books_availableActionPerformed

    private void librarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianActionPerformed
        new Librarian_table().setVisible(true);
        dispose();
    }//GEN-LAST:event_librarianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)studenttable.getModel();
        String query ="SELECT * FROM library_project.student";
        try
        {
            Connection c = Connect.ConnectToDB();
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next())
            {
                int studentid = rs.getInt("STUDENT_ID");
                String firstname = rs.getString("FIRST_NAME");
                String lastname = rs.getString("LAST_NAME");
                String category = rs.getString("STATUS");
                String email = rs.getString("EMAIL");
                String gender = rs.getString("GENDER");
                int phonenumber = rs.getInt("PHONE_NUMBER");
                String yearofstudy = rs.getString("YEAR_OF_STUDY");
                model.addRow(new Object [] {studentid,firstname,lastname,category,email,gender,phonenumber,yearofstudy});
            }
            rs.close();
            stm.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void booktransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktransActionPerformed
       new Borrowing_Trans().setVisible(true);
       dispose();
    }//GEN-LAST:event_booktransActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement pst;
        Connection c=Connect.ConnectToDB();
        try {pst = c.prepareStatement("DELETE  FROM library_project.student WHERE STUDENT_ID = ?");
            pst.setInt(1, Integer.parseInt(delete.getText()));
             pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Record Deleted","Deleted",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        } 


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton books_available;
    private javax.swing.JButton booktrans;
    private javax.swing.JTextField delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton librarian;
    private javax.swing.JButton program;
    private javax.swing.JTable studenttable;
    // End of variables declaration//GEN-END:variables
}
